version: '3.8'

services:
  user-db:
    image: 'mongo:latest'
    restart: always
    container_name: keys-db
    environment:
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_BACKEND_PERMISSIONS=${MONGO_DB_BACKEND_PERMISSIONS}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
    ports:
      - ${MONGO_DB_PORT}:27017
    env_file:
      - .env
    volumes:
      - "./mongodb_data:/data/db"
      - "./MongoSetup.sh:/MongoSetup.sh"
    command: bash -c "sleep 5 && chmod +x /MongoSetup.sh && /MongoSetup.sh"


  auth-db:
    image: redis:alpine
    restart: always
    container_name: keys-redis
    environment:
      - REDIS_SECRET=${REDIS_SECRET}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_SECRET"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env